return {
    Tools = {
        ["Petal Wand"] = {
            Name = "Petal Wand",
            Type = "tools",
            Honey = 1500000000,
            Ingredients = {
                ["Enzymes"] = 75,
                ["Glitter"] = 100,
                ["Star Jelly"] = 10,
                ["Spirit Petal"] = 1
            }
        },
        ["Tide Popper"] = {
            Name = "Tide Popper",
            Type = "tools",
            Honey = 2500000000000,
            Ingredients = {
                ["Blue Extract"] = 1500,
                ["Tropical Drink"] = 150,
                ["Swirled Wax"] = 75,
                ["Super Smoothie"] = 50,
                ["Stinger"] = 200
            }
        },
        ["Dark Scythe"] = {
            Name = "Dark Scythe",
            Type = "tools",
            Honey = 2500000000000,
            Ingredients = {
                ["Red Extract"] = 1500,
                ["Hard Wax"] = 150,
                ["Caustic Wax"] = 75,
                ["Super Smoothie"] = 50,
                ["Stinger"] = 200
            }
        },
        ["Gummy Baller"] = {
            Name = "Gummy Baller",
            Type = "tools",
            Honey = 10000000000000,
            Ingredients = {
                ["Gumdrops"] = 2500,
                ["Glue"] = 1500,
                ["Caustic Wax"] = 50,
                ["Super Smoothie"] = 50,
                ["Turpentine"] = 5
            }
        },
    },
    Masks = {
        ["Diamond Mask"] = {
            Name = "Diamond Mask",
            Type = "masks",
            Honey = 5000000000,
            Ingredients = {
                ["Blue Extract"] = 250,
                ["Oil"] = 150,
                ["Glitter"] = 100,
                ["Diamond"] = 5,
                ["Comforting Vial"] = 1
            }
        },
        ["Gummy Mask"] = {
            Name = "Gummy Mask",
            Type = "masks",
            Honey = 5000000000,
            Ingredients = {
                ["Glue"] = 250,
                ["Oil"] = 100,
                ["Enzymes"] = 100,
                ["Glitter"] = 100,
                ["Satisfying Vial"] = 1
            }
        },
        ["Demon Mask"] = {
            Name = "Demon Mask",
            Type = "masks",
            Honey = 5000000000,
            Ingredients = {
                ["Red Extract"] = 250,
                ["Glue"] = 100,
                ["Enzymes"] = 150,
                ["Stinger"] = 500,
                ["Invigorating Vial"] = 1
            }
        }
    },
    Belts = {
        ["Honeycomb Belt"] = {
            Name = "Honey Belt",
            Type = "belts",
            Honey = 75000000,
            Ingredients = {
                ["Glue"] = 50,
                ["Oil"] = 25,
                ["Enzymes"] = 50
            }
        },
        ["Petal Belt"] = {
            Name = "Petal Belt",
            Type = "belts",
            Honey = 15000000000,
            Ingredients = {
                ["Glue"] = 100,
                ["Glitter"] = 50,
                ["Star Jelly"] = 25,
                ["Spirit Petal"] = 1
            }
        },
        ["Coconut Belt"] = {
            Name = "Coconut Belt",
            Type = "belts",
            Honey = 7500000000000,
            Ingredients = {
                ["Coconut"] = 500,
                ["Tropical Drink"] = 1500,
                ["Purple Potion"] = 200,
                ["Hard Wax"] = 200,
                ["Turpentine"] = 3,
                ["Refreshing Vials"] = 3
            }
        },
    },
    Boots = {
        ["Coconut Boots"] = {
            Name = "Coconut Boots",
            Type = "boots",
            Honey = 10000000000,
            Ingredients = {
                ["Coconut"] = 150,
                ["Glue"] = 100,
                ["Oil"] = 100,
                ["Tropical Drink"] = 50
            }
        },
        ["Gummy Boots"] = {
            Name = "Gummy Boots",
            Type = "boots",
            Honey = 100000000000,
            Ingredients = {
                ["Red Extract"] = 250,
                ["Blue Extract"] = 250,
                ["Glue"] = 500,
                ["Glitter"] = 250
            }
        },
    },
    Bags = {
        ["Coconut Canister"] = {
            Name = "Coconut Canister",
            Type = "bags",
            Honey = 25000000000,
            Ingredients = {
                ["Coconut"] = 150,
                ["Red Extract"] = 100,
                ["Blue Extract"] = 150,
                ["Tropical Drink"] = 150
            }
        },
    },

    Blender = {
        ["Blue Extract"] = {
            ["Blueberry"] = 50,
            ["Royal Jelly"] = 10
        },
        ["Red Extract"] = {
            ["Strawberry"] = 50,
            ["Royal Jelly"] = 10
        },
        ["Enzymes"] = {
            ["Pineapple"] = 50,
            ["Royal Jelly"] = 10
        },
        ["Oil"] = {
            ["Sunflower Seed"] = 50,
            ["Royal Jelly"] = 10
        },
        ["Glue"] = {
            ["Gumdrops"] = 50,
            ["Royal Jelly"] = 10
        },
        ["Tropical Drink"] = {
            ["Coconut"] = 10,
            ["Enzymes"] = 2,
            ["Oil"] = 2
        },
        ["Gumdrops"] = {
            ["Blueberry"] = 3,
            ["Strawberry"] = 3,
            ["Pineapple"] = 3
        },
        ["Glitter"] = {
            ["Moon Charm"] = 25,
            ["Magic Bean"] = 1
        },
        ["Moon Charm"] = {
            ["Pineapple"] = 5,
            ["Gumdrops"] = 5,
            ["Royal Jelly"] = 1
        },
        ["Star Jelly"] = {
            ["Royal Jelly"] = 100,
            ["Glitter"] = 3
        },
        ["Purple Potion"] = {
            ["Neonberry"] = 3,
            ["Red Extract"] = 3,
            ["Blue Extract"] = 3,
            ["Glue"] = 3
        },
        ["Soft Wax"] = {
            ["Honeysuckle"] = 5,
            ["Oil"] = 1,
            ["Enzymes"] = 1,
            ["Royal Jelly"] = 10
        },
        ["Hard Wax"] = {
            ["Soft Wax"] = 3,
            ["Bitterberry"] = 33,
            ["Enzymes"] = 3,
            ["Royal Jelly"] = 33
        },
        ["Swirled Wax"] = {
            ["Hard Wax"] = 3,
            ["Soft Wax"] = 9,
            ["Purple Potion"] = 6,
            ["Royal Jelly"] = 3333
        },
        ["Caustic Wax"] = {
            ["Hard Wax"] = 5,
            ["Enzymes"] = 5,
            ["Neonberry"] = 25,
            ["Royal Jelly"] = 5252
        },
        ["Field Dice"] = {
            ["Soft Wax"] = 1,
            ["Whirligig"] = 1,
            ["Red Extract"] = 1,
            ["Blue Extract"] = 1
        },
        ["Smooth Dice"] = {
            ["Field Dice"] = 3,
            ["Soft Wax"] = 3,
            ["Whirligig"] = 3,
            ["Oil"] = 3
        },
        ["Loaded Dice"] = {
            ["Smooth Dice"] = 3,
            ["Hard Wax"] = 3,
            ["Glue"] = 1,
            ["Oil"] = 3
        },
        ["Super Smoothie"] = {
            ["Neonberry"] = 3,
            ["Star Jelly"] = 3,
            ["Purple Potion"] = 3,
            ["Tropical Drink"] = 6
        },
        ["Turpentine"] = {
            ["Super Smoothie"] = 10,
            ["Caustic Wax"] = 10,
            ["Star Jelly"] = 100,
            ["Honeysuckle"] = 1000
        }
    },
    CurrencyIcons = {
        ["Honey"] = "🍯",
        ["Ticket"] = "🎟️"
    },
    Shops = {
        ["Royal Jelly"] = {
            Price = 1000000,
            Count = 1,
            Currency = "Honey"
        },
        ["Basic"] = {
            Price = 10000000,
            Count = 1,
            Currency = "Honey"
        },
        ["Treat"] = {
            Price = 10000,
            Count = 1,
            Currency = "Honey"
        },

        ["Magic Bean"] = {
            Price = 20,
            Count = 1,
            Currency = "Ticket"
        },
        ["Stinger"] = {
            Price = 10,
            Count = 1,
            Currency = "Ticket"
        },
        ["Gumdrops"] = {
            Price = 1,
            Count = 3,
            Currency = "Ticket"
        }
        -- ["Ticket"] = function(count: number): number
        --     local n = count;
        --     local t = ?;
        --     return (n*(2 * t + 4000 * (n - 1)) / 2)
        -- end,
    }
};
